# Generated by Django 3.0.4 on 2020-03-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
